module.exports = {
  Rare: [
    "Tyrum",
    "Oberon",
    "Prisca",
    "Renfeld",
    "Balthazar",
    "Azar",
    "Hawkmoon",
    "Jahangir",
    "Nashgar",
    "Dawa",
    "Kailani",
    "Gan Ju",
    "Bane",
    "Karil",
    "Graymane",
    "Valen",
    "Gunnar",
    "Ulmer",
    "Isshtak",
    "Belith",
    "Friar Tuck",
    "Brienne",
    "Carver",
    "Berden"
  ],
  Epic: [
    "Sabina",
    "Cyprian",
    "Tiburtus",
    "Rigard",
    "Scarlett",
    "Boldtusk",
    "Gormek",
    "Kelile",
    "Colen",
    "Li Xiu",
    "Hu Tao",
    "Chao",
    "Wu Kong",
    "Sonya",
    "Grimm",
    "Kiril",
    "Boril",
    "Skittleskull",
    "Caedmon",
    "Melendor",
    "Little John",
    "Kashhrek"
  ],
  Legendary: [
    "Sartana",
    "Domitia",
    "Quintus",
    "Obakan",
    "Elena",
    "Khagan",
    "Marjana",
    "Azlar",
    "Leonidas",
    "Justice",
    "Vivica",
    "Joon",
    "Thorne",
    "Magni",
    "Richard",
    "Isarnia",
    "Horghall",
    "Lianna",
    "Elkanen",
    "Kadilen"
  ],
  "Rare Atlantis": [
    "Gill-Ra",
    "Chochin",
    "Mnesseus",
    "Gato",
    "Namahage",
    "Melia",
    "Muggy"
  ],
  "Epic Atlantis": [
    "Ameonna",
    "Proteus",
    "Agwe",
    "Gadeirus",
    "Triton",
    "Wilbur",
    "Gobbler",
    "Sumitomo",
    "Danzaburo"
  ],
  "Legendary Atlantis": [
    "Mok-Arr",
    "Tarlak",
    "Misandra",
    "Kageburado",
    "Mitsuko",
    "Inari",
    "Atomos",
    "Ariel",
    "Poseidon",
    "Ursena"
  ],
  "Featured Legendary": ["FEATURED HERO"]
};
